version: 2

sources:
  - name: raw #Renaming as an alias
    schema: gz_raw_data #Path of the table in BQ
    description: greenwez raw data source #optional
    tables:
      - name: sales #Renaming as an alias
        identifier: raw_gz_sales #What is the exact name of the table in  BQ
        description: sales of greenweez / we have one row per product_id found in each order_id
        columns:
          - name: "(orders_id || '-' || pdt_id)"
            description: primary key of the table
            tests:
              - unique
              - not_null
        config: # Freshness checks are added under config key
          loaded_at_field: CAST(date_date AS TIMESTAMP) # Date cast
          freshness:
            warn_after: { count: 90, period: day }

      - name: product
        identifier: raw_gz_product
        description: purchase_price by products_id
        columns:
          - name: products_id
            description: primary key of the table
            tests:
              - unique
              - not_null

      - name: ship
        identifier: raw_gz_ship
        description: ship and log costs
        columns:
          - name: orders_id
            description: primary key of the table
            tests:
              - unique
              - not_null

models:
  - name: int_sales_margin #dbt path
    description: margin per product calculation #calculation
    columns:
      - name: "(orders_id || '-' || products_id)"
        description: primary key of the table
        tests:
          - unique
          - not_null
      - name: products_id
        tests:
          - not_null
      - name: date_date
        tests:
          - not_null
      - name: orders_id
        tests:
          - not_null
      - name: revenue
        tests:
          - not_null
      - name: quantity
        tests:
          - not_null
      - name: purchase_price
        tests:
          - not_null
      - name: margin
        tests:
          - not_null
      - name: purchase_cost
        tests:
          - not_null

  - name: finance_days
    description: daily financial metrics
    columns:
      - name: date_date
        description: primary key of the table
        tests:
          - unique
          - not_null
      - name: total_number_of_transactions
        tests:
          - not_null
      - name: total_revenue
        tests:
          - not_null
      - name: average_basket
        tests:
          - not_null
      - name: operational_margin
        tests:
          - not_null
      - name: total_purchase_cost
        tests:
          - not_null
      - name: total_shipping_fees
        tests:
          - not_null
      - name: total_logcost
        tests:
          - not_null
      - name: total_qty_products_sold
        tests:
          - not_null

  - name: int_orders_operational
    description: "Order-level model including revenue, margin, shipping costs, and operational margin."
    columns:
      - name: orders_id
        description: primary key of the table
        tests:
          - unique
          - not_null
      - name: date_date
        tests:
          - not_null
      - name: revenue
        tests:
          - not_null
      - name: quantity
        tests:
          - not_null
      - name: purchase_cost
        tests:
          - not_null
      - name: margin
        tests:
          - not_null
      - name: shipping_fee
        tests:
          - not_null
      - name: logcost
        tests:
          - not_null
      - name: ship_cost
        tests:
          - not_null
      - name: operational_margin
        tests:
          - not_null

  - name: int_orders_margin
    description: Calculate the Margin per Order
    columns:
      - name: orders_id
        description: primary key
        tests:
          - unique
          - not_null
      - name: date_date
        tests:
         - not_null
      - name: revenue
        tests:
         - not_null
      - name: quantity
        tests:
         - not_null
      - name: purchase_cost
        tests:
         - not_null
      - name: margin
        tests:
         - not_null    


